const ListActionTypes = {
    LOAD_LIST_START: 'LOAD_LIST_START',
    LOAD_LIST_SUCCESS: 'LOAD_LIST_SUCCESS',
    LOAD_LIST_FAILURE: 'LOAD_LIST_FAILURE',
    ADD_TO_LIST_START: 'ADD_TO_LIST_START',
    ADD_TO_LIST_SUCCESS: 'ADD_TO_LIST_SUCCESS',
    ADD_TO_LIST_FAILURE: 'ADD_TO_LIST_FAILURE'
}
export default ListActionTypes